name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "*"
      
jobs:
  ci:
    uses: e-scooter-2077/azure-functions-ci/.github/workflows/azure-functions-ci.yml@master
    with:
      release-prefix: Azure Function Template
      azure-functionapp-name: ''
      project-name: ''
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

